land/urls.py
__author__ = 'hudutech'

from django.conf.urls import url
from land import views
urlpatterns = [
    url(r'^$', views.login_user, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.my_profile, name='profile'),
    url(r'^register-land/$', views.register_land, name='register_land'),
    url(r'^transfer-land/(?P<pk>[0-9])/$', views.transfer_land, name='transfer_land'),
    url(r'^my-lands/$', views.my_land_list, name='mylands'),
    url(r'^my-lands/details/(?P<title_deed>[-\w]+)/$', views.land_details, name='land_details'),
    url(r'^lands-onsale/$', views.land_on_sale, name='lands_onsale'),
    url(r'^lands-onsale/land-details/(?P<title_deed>[-\w]+)/$', views.land_details, name='landonsaledetail'),
    url(r'^contact-us/$', views.contact_us, name='contactus'),
    url(r'^lands-bought/$', views.lands_bought, name='lands_bought'),
    url(r'^notifications/(?P<user>[-\w]+)/$', views.get_notification, name='notification'),
    url(r'^approve/(?P<title_deed>[-\w]+)/$', views.approve_purchased_land, name='approve'),
    url(r'^reject/(?P<title_deed>[-\w]+)/$', views.reject_purchased_land, name='reject'),
    url(r'^lands-onsale/search/$', views.search_land_onsale, name='search', ),
    url(r'^mypurchasedlands/$', views.show_land_purchased, name='mypurchase', ),


]

payments/urls.py
__author__ = 'hudutech'

from django.conf.urls import url
from payments import views
urlpatterns = [
    url(r'^transfer/(?P<pk>[0-9])/$', views.land_transfer_payment, name='transfer_payment'),
    url(r'^purchase/(?P<pk>[0-9])/$', views.purchase_land, name='purchase'),
    url(r'^callback/$', views.mpesa_notification_callback, name='callback'),
    url(r'^fee-history/$', views.transaction_history, name='history'),
    url(r'^process/$', views.land_payment_process, name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^canceled/$', views.payment_canceled, name='cancelled'),

]

smartland/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'smartland.views.home', name='home'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^', include('land.urls', namespace='land')),


    url(r'^admin/', include(admin.site.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'SmartLand'

land/forms.py
__author__ = 'hudutech'

from django import forms
from django.contrib.auth.models import User
from land.models import LandUserProfile, Land, LandTransfers


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=32, )
#     password = forms.CharField(max_length=32, widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=32, widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', max_length=32, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class LandUserProfileForm(forms.ModelForm):

    class Meta:
        model = LandUserProfile
        exclude = ('user', )


class LandRegistrationForm(forms.ModelForm):

    class Meta:
        model = Land
        exclude = ('user', 'purchased', 'fee_paid', )


class LandTransferForm(forms.Form):
    title_deed = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'title_deed_id', }
    ),)

    transfer_to = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'transfer_to_id', }
    ), label='Transfer_to(Username)')

    relationship = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'relationship_id', 'placeholder': 'Enter relationship eg(brother, son, daughter)'}
    ))

    transfer_size = forms.FloatField()


class LandPurchaseForm(forms.Form):
    title_deed = forms.CharField(max_length=32, disabled=True)
    phone_number = forms.CharField(max_length=10, widget=forms.TextInput(
        attrs={'placeholder': '07XX XXX XXX'}
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': 'Your Email Address'}
    ))
    deposit = forms.DecimalField(max_digits=10, decimal_places=2, disabled=True)


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=32)
    phone_number = forms.CharField(max_length=10, widget=forms.TextInput(
        attrs={'id': 'phone_number_id', 'placeholder': '07 XX XXX XXX'}
    ))
    email = forms.EmailField()
    message = forms.CharField(max_length=140, widget=forms.Textarea(
        attrs={'id': 'message_id', 'placeholder': 'Your message here ....'}
    ))


class SearchLandForm(forms.Form):
    minimum_price = forms.FloatField(widget=forms.NumberInput(
        attrs={'id': 'minimum_price_id',  'placeholder': 'Enter minimum price'},
    ))
    maximum_price = forms.FloatField(widget=forms.NumberInput(
        attrs={'id': 'maximum_price_id',  'placeholder': 'Enter maximum price'},
    ))
    land_size = forms.FloatField(widget=forms.NumberInput(
        attrs={'id': 'land_size_id', 'placeholder': 'Enter Land Size', }
    ))

    land_location = forms.CharField(max_length=32, widget=forms.TextInput(
        attrs={'id': 'land_location_id', 'placeholder': 'Enter location to search', }
    ))

land/views.py
from django.shortcuts import render, render_to_response, get_object_or_404
from django.http.response import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import IntegrityError
from django.db.models import Q

from land.forms import (
    UserRegistrationForm,
    LandUserProfileForm,
    LandRegistrationForm,
    LandTransferForm,
    LandPurchaseForm,
    SearchLandForm,
    ContactForm,
)
from land.models import (
    LandUserProfile,
    Land,
    LandTransfers,
    LandPurchases,
    ContactUs,
    Notification,
)

from payments.models import LandTransferPayment

from land.phoneNumber import CleanPhoneNumber

from random import randint


@require_http_methods(['POST', 'GET'])
def login_user(request):
    next_url = request.GET.get('next', '')
    #check if user is authenticated and redirect user to root page
    if request.user.is_authenticated():
            return HttpResponseRedirect('/index/')

    # if not request.user.is_authenticated():
    #         return HttpResponseRedirect('/login/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        print 'username', username
        print 'password', password
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)

                if next_url == '':
                    return HttpResponseRedirect('/index/')
                elif next_url:
                    return HttpResponseRedirect(next_url)
        else:
            err_message = 'Wrong username / password'
            return render(request, 'land/login.html', {'err_message': err_message, })
    else:
        return render(request, 'land/login.html', )


@login_required(login_url='/login/')
def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/login/')


def signup(request):
    if request.method == 'POST':
        signup_form = UserRegistrationForm(request.POST)
        profile_form = LandUserProfileForm(request.POST)
        if signup_form.is_valid() and profile_form.is_valid():
            user = signup_form.save(commit=False)
            user.set_password(signup_form.cleaned_data['password2'])
            user.save()
            data = profile_form.cleaned_data
            id_no = data['id_no']
            phone_number = data['phone_number']
            clean_phone_number = CleanPhoneNumber(phone_number).validate_phone_number()
            profile = LandUserProfile.objects.create(
                user=user,
                id_no=id_no,
                phone_number=clean_phone_number
            )
            profile.save()
            success_message = 'Account created successfully'
            return render(request, 'land/signup.html', {'success_message': success_message})
    else:
        signup_form = UserRegistrationForm()
        profile_form = LandUserProfileForm()
    return render(request, 'land/signup.html',
                  {
                      'signup_form': signup_form,
                      'profile_form': profile_form
                  })


@login_required(login_url='/login/')
def my_profile(request):

    profile = get_object_or_404(
        LandUserProfile,
        user=get_object_or_404(User, username=request.user)
    )
    return render(request, 'land/myprofile.html', {'profile': profile, })


@login_required(login_url='/login/')
def register_land(request):
    user = get_object_or_404(User, username=request.user)
    profile = get_object_or_404(LandUserProfile, user=user)
    if request.method == 'POST':
        land_form = LandRegistrationForm(request.POST, request.FILES)
        if land_form.is_valid():
            cd = land_form.cleaned_data
            title_deed = cd['title_deed']
            location = cd['location']
            size = cd['size']
            photo = cd['photo']
            description = cd['description']
            on_sale = cd['on_sale']
            land_value = cd['land_value']
            map_sheet = cd['map_sheet']
            land_obj = Land.objects.create(
                user=profile,
                title_deed=title_deed,
                location=location,
                map_sheet=map_sheet,
                size=size,
                photo=photo,
                description=description,
                on_sale=on_sale,
                land_value=land_value
            )
            land_obj.save()
            success_message = 'Land registered successfully'
            return render(request, 'land/register_land.html', {'success_message': success_message})
    else:
        land_form = LandRegistrationForm()
    return render(request, 'land/register_land.html', {'land_form': land_form, })


@login_required(login_url='/login/')
def transfer_land(request, pk=None):
    land = get_object_or_404(Land, pk=pk)
    title_deed = str(land.title_deed)
    initial = {'title_deed': title_deed, }
    if request.method == 'POST':

        transfer_form = LandTransferForm(request.POST, initial=initial)
        if transfer_form.is_valid():
            cd = transfer_form.cleaned_data
            size_transferred = cd['transfer_size']
            relationship = cd['relationship']
            transfer_to = cd['transfer_to']

            range_start = 10 ** (10 - 1)
            range_end = (10 ** 10) - 1
            new_title_deed = randint(range_start, range_end)

            user = get_object_or_404(User, username=request.user)
            profile = get_object_or_404(LandUserProfile, user=user)
            try:

                payment = LandTransferPayment.objects.get(title_deed=title_deed, transferred_size=size_transferred)
                if payment.status == 'Success':
                    land_transfer_obj = LandTransfers.objects.create(
                        title_deed=land,
                        new_title_deed=new_title_deed,
                        owner=profile,
                        transfer_to=transfer_to,
                        size_transferred=size_transferred,
                        relationship=relationship
                    )
                    land_transfer_obj.save()
                    success_message = 'Land Transferred Successfully!'
                    return render(request, 'land/transfer_land.html',
                                  {'success_message': success_message})

                else:
                    return HttpResponse('Please make the payment first')
            except LandTransferPayment.DoesNotExist:
                return HttpResponse('Please make the payment first')

    else:
        transfer_form = LandTransferForm()
    return render(request, 'land/transfer_land.html', {'transfer_form': transfer_form, })


@login_required(login_url='/login/')
def my_land_list(request):
    user = get_object_or_404(User, username=request.user)
    profile = get_object_or_404(LandUserProfile, user=user)
    lands = Land.objects.filter(user=profile, purchased=False)

    return render(request, 'land/my_land_list.html', {'lands': lands}, )


def land_details(request, title_deed=None):
    try:
        land = Land.objects.get(title_deed=title_deed)
        return render(request, 'land/land_details.html', {'land': land, })
    except Land.DoesNotExist:
        message = 'No land that matches the supplied title deed'
        return render(request, 'land/land_details.html', {'error': message})


@login_required(login_url='/login/')
def land_on_sale(request):
    user = get_object_or_404(LandUserProfile, user=get_object_or_404(User, username=str(request.user)))
    lands = Land.objects.filter(on_sale=True).exclude(Q(user=user))
    return render(request, 'land/lands_onsale.html', {'lands': lands, })


@login_required(login_url='/login/')
def lands_bought(request):
    user = get_object_or_404(User, username=request.user)
    lands = LandPurchases.objects.filter(owner=user, paid=True)
    return render(request, 'land/lands_bought.html', {'lands_bought': lands})


def index(request):
    return render(request, 'index.html', {})


def contact_us(request):
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)

        if contact_form.is_valid():
            cd = contact_form.cleaned_data
            first_name = cd['first_name']
            last_name = cd['last_name']
            email = cd['email']
            phone_number = cd['phone_number']
            message = cd['message']
            clean_phone_number = CleanPhoneNumber(phone_number).validate_phone_number()

            contact = ContactUs.objects.create(
                first_name=first_name,
                last_name=last_name,
                email=email,
                phone_number=clean_phone_number,
                message=message
            )
            contact.save()
            success_message = 'Message Sent Successfully'
            return render(request, 'land/contactus.html', {'success_message': success_message})

    else:
        contact_form = ContactForm()
    return render(request, 'land/contactus.html', {'contact_form': contact_form, })


@login_required(login_url='/login/')
def get_notification(request, user):
    user = get_object_or_404(User, username=user)
    notification = Notification.objects.filter(user=user).order_by('date')
    return render(request, 'land/notification.html', {'notification': notification, })


@login_required(login_url='/login/')
def approve_purchased_land(request, title_deed):
    land_obj = get_object_or_404(Land, title_deed=title_deed)
    land = get_object_or_404(LandPurchases, land=land_obj, paid=True)
    land.approved = True
    land.rejected = False
    land.save()
    message = 'Land Purchase approved successfully'

smartland/templates/land/approve_success.html
{% extends 'base.html' %}

{% block content %}

    <div class="col col-md-6">
    {% if success_message %}
        <div class="alert alert-success" role="alert">
            <strong>{{ success_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    </div>
{% endblock %}

smartland/templates/land/contactus.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col col-md-8">
        {% if success_message %}
            <div class="alert alert-success" role="alert">
                <strong>{{ success_message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% else %}
        <form action="" method="post">
            {% csrf_token %}
            {{ contact_form | crispy }}
            <input type="submit" value="Submit" class="btn btn-primary btn-raised">
        </form>
    {% endif  %}
</div>
{% endblock %}

smartland/templates/land/land_details.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="col col-md-8">

        <div class="panel panel-inverse">
            <p class="panel-heading" style="padding-left: 15px;">More Details About the Land</p><br>

            <p class="panel" style="margin-left: 4px!important;">
                Location {{ land.description }}<br>
                Title Deed Number: {{ land.title_deed }}<br>
                Map Sheet Number: {{ land.map_sheet }}<br>
                Land Size: {{ land.size }} acres<br>
                {% if land.on_sale %}Land Price: Ksh {{ land.land_value }}{% endif %}
            </p>

            <p class="" style="padding: 15px;">Owner Details</p>
            <div class="profile-avartar ">
                        {% if land.user.profile_image %}
                            <img src="{{ land.user.profile_image.url }}" alt="{{ profile.user.username }}"
                                 class="profile-avartar">
                        {% else %}
                            <img src="{% static 'img/no-profile-image.jpg' %}" class="profile-avartar">
                        {% endif %}
             </div>
           <br>
            <p class="panel panel-info">
               Full Name:  {{ land.user.user.first_name }} &nbsp; {{ land.user.user.last_name }}<br>
            National ID: {{ land.user.id_no }}<br>
            Contact(mobile number): {{ land.user.phone_number }}<br>
            Email: {{ land.user.user.email }}<br>
            </p>
        </div>

    </div>

{% endblock %}

smartland/templates/land/lands_onsale.html
{% extends 'base.html' %}

{% block content %}
<div class="col col-md-10">
        {% if lands %}

        <!---Search Land form Modal-->

        <!--End of  Search Land form modal-->

        <h1>Land Available For Sale</h1>
        <p>
            <a href="{% url 'land:search' %}" class="btn btn-inverse btn-raised pull-right "> Go to Land Finder</a></p>
        <table class="table table-responsive" border="2px">
            <tr>
                <td>Title Deed</td>
                <td>Map Sheet</td>
                <td>Size</td>
                <td>Location</td>
                <td>Price</td>
                <td>Link</td>
                <td>Details Link</td>
            </tr>
            {% for land in lands %}
                <tr>
                    <td>{{ land.title_deed }}</td>
                    <td>{{ land.map_sheet }}</td>
                    <td>{{ land.size }}</td>
                    <td>{{ land.location }}</td>
                    <td>{{ land.land_value }}</td>
                    <td><a href="{% url 'payments:purchase' pk=land.pk %}">Purchase Now</a></td>
                    <td><a href="{% url 'land:landonsaledetail' title_deed=land.title_deed %}">More Details about this land</a></td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <div class="alert alert-danger" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
             <strong>No lands Available for sale</strong>
            </div>
        {% endif %}
</div>
{% endblock %}

smartland/templates/land/login.html
{% load staticfiles %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} SmartLand  System {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include 'main_css.html' %}
    {% include 'signup_custom_css.html' %}
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">

            <h1 class="text-center login-title">Sign in to continue to SmartLand</h1>
            <div class="account-wall">
                <img class="profile-img" src="{% static 'img/pic.png' %}"
                    alt="SmartLand">

                 {% if err_message %}
                   <div class="alert alert-danger alert-dismissable" style="margin-left: 10px; margin-right: 10px;">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <p>{{ err_message }}</p>
                </div>
                 {% endif %}
                <form class="form-signin" action=""  method="post">
                <input type="text" class="form-control" placeholder="Username/email" name="username" required autofocus>
                <input type="password" class="form-control" placeholder="Password"  name="password" required>
                <button class="btn btn-lg btn-inverse btn-block btn-raised" type="submit">
                    Sign in</button>
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember Me
                </label>
                <a href="#" class="pull-right need-help">Need help? </a><span class="clearfix"></span>
               {% csrf_token %}
                </form>
            </div>
            <a href="{% url 'land:signup' %}" class="text-center new-account">Create an account </a>
        </div>
    </div>
</div>
{% include 'main_scripts.html' %}
</body>
</html>

smartland/templates/land/my_land_list.html
{% extends 'base.html' %}


{% block content %}
    <div class="col col-md-10">
       {% if lands %}
        {% for land in lands %}
                <div class="panel panel-inverse">
                    <div class="panel-heading">
                        SmartLand (Title Deed: {{ land.title_deed }} )
                    </div>
                    <div class="panel-body">
                        <div class="thumbnail">
                            <img src="{{ land.photo.url }}" height="250" width="600" class="img img-responsive">
                        </div>
                    </div>
                    <div class="panel-footer">
                   <p>Land Size: ({{ land.size }} hectors)</p>
                    <p>Location: ({{ land.location }}) </p>
                    <p>{% if land.title_deed_scan %}<a href="{{ land.title_deed_scan.url }}">TITLE DEED PDF SCAN LINK</a> {% endif %}</p>
                        <p>Description
                            <a href="{% url 'land:land_details' title_deed=land.title_deed %}" class="">
                                Read More...</a>
                        </p>
                    <p>
             <a href="{% url 'payments:transfer_payment' pk=land.pk %}" class="btn btn-inverse btn-raised
                         {% if land.fee_paid %} disabled {% endif %}" style="font-size: 14px!important;">Pay Land Transfer Fee</a>

                          <a href="{% url 'land:transfer_land' pk=land.pk %}" class="btn btn-danger btn-raised
                           {% if not land.fee_paid %} disabled {% endif %}">Transfer Land</a>

                        </p>
                    </div>
                </div>

        {% endfor %}
    {% else %}
    <div class="alert alert-info">
        <p>You dont have any land registered in the system <a href="{% url 'land:register_land' %}"> Click Here</a> To register Land with us</p>
    </div>
    {% endif %}
    </div>
{% endblock %}

smartland/templates/land/myland_purchases.html
{% extends 'base.html' %}


{% block content %}
<div class="col col-md-10">
{% if purchased_lands %}
    <table class="table table-responsive">
    <thead>
    <th>Land Title Deed</th>
    <th>Purchased From</th>
    <th>Deposit Amount</th>
    <th>Date Purchased</th>
    </thead>
    {% for land in purchased_lands %}
        <tr>
        <td>{{ land.land.title_deed }}</td>
        <td>{{ land.owner.username }}</td>
        <td>{{ land.deposit }}</td>
        <td>{{ land.date }}</td>
        </tr>
    {% endfor %}
    </table>
  {% else %}

    <div class="alert alert-info">
    <p>You have not purchased any land <a href="{% url 'land:lands_onsale' %}" >Click here to purchase</a></p>
    </div>

{% endif %}
</div>
{% endblock %}

smartland/templates/land/notification.html
{% extends 'base.html' %}
{% block content %}


    <div class="col col-md-10">
        {% if not notification %}
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p>You have no notifications</p>
            </div>
        {% else %}
            {% for n in notification %}
                <div class="alert alert-primary alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true" style="color: white!important; height: 65px!important;">&times;</span>
                    </button>
                    {{ n.message }}<br>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

smartland/templates/land/purchase_land.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col col-md-10">
    {% if success_message %}
        <div class="alert alert-success" role="alert">
            <strong>{{ success_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>

     {% elif error %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ error }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
         </div>
    {% else %}
     <div class="">
     <div class="">
         <p>Make Land Deposit Payment using Mpesa.</p>
         <ul class="list-group">
             <li class="list-group-item">How it works.</li>
                <li class="list-group-item">Step 1: Enter you phone number in the form below</li>
                <li class="list-group-item">Step 2: Click on the mobile checkout button</li>
                <li class="list-group-item">Step 3: Check your mobile phone and complete the payment by accepting. done!!</li>
         </ul>
     </div>
       <div class="img-thumbnail">
                <img src="{%  static 'img/mpesa.png' %}">
       </div>

       </div>

        <form action="" method="post">
            {% csrf_token %}
            {{ purchase_form | crispy }}
            <input type="submit" value="mobile checkout-->" class="btn btn-primary btn-raised">
        </form>
    {% endif %}
</div>
{% endblock %}

smartland/templates/land/register_land.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col col-md-10">
        {% if success_message %}

            <div class="alert alert-danger" role="alert" style="margin-left: 10px;margin-right: 10px; ">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
               <span>
                   <strong>{{ success_message }}</strong>
                   Click<a href="{% url 'land:mylands' %}">here to view my registered lands</a>
               </span>

            </div>
        {% else %}
            <p class="btn btn-inverse">Register Your Land With SmartLand System By Filling the Form Below</p>
            <form action="" method="post" enctype="multipart/form-data">
                <table class="table table-responsive table-bordered">
                    {{ land_form.as_table }}
                    {% csrf_token %}
                </table>
                <div class="col col-md-12 col-md-offset-4">
                    <input type="submit" value="Register Land" class="btn btn-inverse btn-raised">
                </div>

            </form>

        {% endif %}
    </div>
{% endblock %}

smartland/templates/land/reject_success.html
{% extends 'base.html' %}

{% block content %}
    <div clas="col col-md-10">
    {% if success_message %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ success_message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    </div>

{% endblock %}

smartland/templates/land/signup.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %} SmartLand  System {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include 'main_css.html' %}
    <style type="text/css">
        .profile-avatar{
             border-radius: 100%;
             height: 150px;
             width: 150px;
{#             box-shadow: 2px;#}
             align-self: center;

             margin-top: 35px;
             background: none;

         }
    </style>
</head>
<body>
<div class="container">

    <div class="row">

        <div class="col col-md-6 col-md-offset-3">

            <div>
                <div class="col col-md-6 col-md-offset-3 profile-avatar">
                    <img src="{% static 'img/pic.png' %}">
                     <p class="btn btn-primary" style="margin: 2px;">Please Register Here</p>
                </div>

            </div>
            <div class="card jumbotron">

                {% if success_message %}
                    <strong> {{ success_message }} <a href="{% url 'land:login' %}"> click here to Sign
                        In</a></strong>


                {% else %}
                    <form action="" method="post" style="padding: 2px; margin: 4px;">
                        {% csrf_token %}
                        <table class="table table-responsive">
                        {{ profile_form.as_table }}
                        {{ signup_form.as_table }}
                        </table>
                        <input type="submit" value="Sign Up" class="btn btn-inverse btn-raised">
                       <p>Already have an account ? <a href="{% url 'land:login' %}">Sign in</a> </p>
                    </form>
                {% endif %}

        </div>
    </div>
</div>
</div>
</body>
{% include 'main_scripts.html' %}
</html>