land/urls.py
__author__ = 'hudutech'

from django.conf.urls import url
from land import views
urlpatterns = [
    url(r'^$', views.login_user, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^profile/$', views.my_profile, name='profile'),
    url(r'^register-land/$', views.register_land, name='register_land'),
    url(r'^transfer-land/(?P<pk>[0-9])/$', views.transfer_land, name='transfer_land'),
    url(r'^my-lands/$', views.my_land_list, name='mylands'),
    url(r'^my-lands/details/(?P<title_deed>[-\w]+)/$', views.land_details, name='land_details'),
    url(r'^lands-onsale/$', views.land_on_sale, name='lands_onsale'),
    url(r'^lands-onsale/land-details/(?P<title_deed>[-\w]+)/$', views.land_details, name='landonsaledetail'),
    url(r'^contact-us/$', views.contact_us, name='contactus'),
    url(r'^lands-bought/$', views.lands_bought, name='lands_bought'),
    url(r'^notifications/(?P<user>[-\w]+)/$', views.get_notification, name='notification'),
    url(r'^approve/(?P<title_deed>[-\w]+)/$', views.approve_purchased_land, name='approve'),
    url(r'^reject/(?P<title_deed>[-\w]+)/$', views.reject_purchased_land, name='reject'),
    url(r'^lands-onsale/search/$', views.search_land_onsale, name='search', ),
    url(r'^mypurchasedlands/$', views.show_land_purchased, name='mypurchase', ),


]

payments/urls.py
__author__ = 'hudutech'

from django.conf.urls import url
from payments import views
urlpatterns = [
    url(r'^transfer/(?P<pk>[0-9])/$', views.land_transfer_payment, name='transfer_payment'),
    url(r'^purchase/(?P<pk>[0-9])/$', views.purchase_land, name='purchase'),
    url(r'^callback/$', views.mpesa_notification_callback, name='callback'),
    url(r'^fee-history/$', views.transaction_history, name='history'),
    url(r'^process/$', views.land_payment_process, name='process'),
    url(r'^done/$', views.payment_done, name='done'),
    url(r'^canceled/$', views.payment_canceled, name='cancelled'),

]

smartland/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'smartland.views.home', name='home'),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payments/', include('payments.urls', namespace='payments')),
    url(r'^', include('land.urls', namespace='land')),


    url(r'^admin/', include(admin.site.urls)),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'SmartLand'

smartland/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %} SmartLand  System {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- my local css and bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <!--font awesome -->
    <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %} " rel="stylesheet">
    <!-- sidebar-->
    <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">


    {#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>#}

    {#    css for material#}
    <link href="{% static 'material/css/bootstrap-material-design.css' %}" rel="stylesheet">
    <link href="{% static 'material/css/ripples.min.css' %}" rel="stylesheet">
    <!-- slider css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}">
    <!--end of slider css -->


    <!--end of my local -->


    {#    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>#}
    {#    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>#}
    <style type="text/css">
        /* Remove the navbar's default rounded borders and increase the bottom margin */
        .navbar {
            margin-bottom: 50px;
            border-radius: 0;
        }

        .profile-avartar {
            height: 150px;
            width: 150px;
            border-radius: 50%;
            -webkit-border-radius: 50%;
            -moz-border-radius: 50%;
            text-align: center;
        }

        .custom {
            background-color: #ffffff;
            background-repeat: repeat;

            background-color: transparent;
        {#            background-image: url('{% static 'img/backgroud2.jpeg' %}');#} {#            -moz-border-corner-image: 0px;#} {#            opacity: 10px;#} {#            image-rendering: optimize-contrast;#}
        }

        /* Remove the jumbotron's default bottom margin */
        .jumbotron {
            margin-bottom: 0;

        }

        /* Add a gray background color and some padding to the footer */
        .footer {
            background: #f7e1b5!important;
            padding: 25px;

        }
    </style>
</head>
<body class="custom">
{#<div class="jumbotron">#}
{#    <div class="container text-center">#}
{#        <h1>Nyeri Land Admistration System  </h1>#}
{#    </div>#}
{#</div>#}

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'land:index' %}">SmartLand </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">

            <ul class="nav navbar-nav">

                <li class="active"><a href="{% url 'land:index' %}">Home</a></li>
                <li><a href="#">About</a></li>

                <li><a href="{% url 'land:contactus' %}">Contact Us</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'land:lands_onsale' %}">Lands Onsale</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Services
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Services</li>
                            <li><a href="{% url 'land:register_land' %}"> Register Land</a></li>
                            <li><a href="{% url 'land:mylands' %}">View My Lands</a></li>
                            <li><a href="{% url 'land:lands_onsale' %}">Purchase Land</a></li>
                            <li><a href="http://www.ardhi.go.ke">Resources Website</a> </li>


                        </ul>
                    </li>


                {% else %}
                    <li><a href="{% url 'land:signup' %}">Create Account</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">My Profile
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li class="dropdown-header">Profile</li>
                            <li><a href="{% url 'land:profile' %}">Account</a> </li>
                            <li><a href="{% url 'land:lands_bought' %}">Lands Bought</a></li>
                            <li><a href="{% url 'land:mylands' %}"> My Lands</a></li>
                            <li><a href="{% url 'land:mypurchase' %}"> My Land Purchase</a></li>

                        </ul>
                    </li>

                    <li><a href="{% url 'land:notification' user=request.user %}"><span
                            class="glyphicon glyphicon-globe"></span>
                        Notifications</a></li>

                    <li><a href="#"><span class="glyphicon glyphicon-user"></span>
                    {{ request.user }}
                    <li><a href="{% url 'land:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                    </li>
                {% else %}
                    <li><a href="{% url 'land:login' %}"><span class="glyphicon glyphicon-log-out"></span> Login</a>
                    </li>

                {% endif %}</a></li>

            </ul>
        </div>
    </div>
</nav>


<div class="row" style="">
    <div class="content">
        <div class="col col-md-3">

            {% block sidebar %}
                <div>
                    {% if user.is_authenticated %}
                        {% include 'side_bar.html' %}
                    {% endif %}
                </div>
            {% endblock %}

        </div>
        <div class="col col-md-9">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>

</body>

smartland/templates/css.html
{% load staticfiles %}
<link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <!--font awesome -->
<link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %} " rel="stylesheet">
<!-- sidebar-->
<link href="{% static 'css/sidebar.css' %}" rel="stylesheet">

{#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>#}

{#    css for material#}
<link href="{% static 'material/css/bootstrap-material-design.css' %}" rel="stylesheet">
<link href="{% static 'material/css/ripples.min.css' %}" rel="stylesheet">
<!-- slider css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}">

smartland/templates/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">

   <div class="jumbotron col col-md-10" style="margin-left: 25px !important;">
   <h4><strong>Welcome to SmartLand System. The Future Of The Land Management In Kenya</strong></h4>

   <p>SmartLand is a Land Management System that allows all its users to register their Lands
   in an online Account. It makes the process of land Transfer and Purchasing way far much easier.
   SmartLand Embraces the use of mobile money transfer especially <strong>Mpesa</strong> Which is the
   leading mobile money transfer in Kenya.

   By embracing this technology the Smartland users only need their mobile devices to make transactions in the
   system.
   You can check the available lands,  register lands and pay for land transfer Fees just by a click of a button from
       the comfort of your phone
   </p>

   </div>
</div>
{% endblock %}

smartland/templates/main_css.html
{% load staticfiles %}
<link href="{% static 'css/bootstrap.min.css' %} " rel="stylesheet">
    <!--font awesome -->
<link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %} " rel="stylesheet">
<!-- sidebar-->
<link href="{% static 'css/sidebar.css' %}" rel="stylesheet">

{#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>#}

{#    css for material#}
<link href="{% static 'material/css/bootstrap-material-design.css' %}" rel="stylesheet">
<link href="{% static 'material/css/ripples.min.css' %}" rel="stylesheet">
<!-- slider css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.bxslider.css' %}">

smartland/templates/main_scripts.html
{% load staticfiles %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} "></script>
<!--material js-->
<script src="{% static 'material/js/material.min.js' %}"></script>
<script src="{% static 'material/js/ripples.min.js' %}"></script>
<script>
    $(function () {
        $.material.init();
    });
</script>

smartland/templates/scripts.html
{% load staticfiles %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} "></script>
<!--material js-->
<script src="{% static 'material/js/material.min.js' %}"></script>
<script src="{% static 'material/js/ripples.min.js' %}"></script>
<script>
    $(function () {
        $.material.init();
    });
</script>

smartland/templates/side_bar.html
{% load staticfiles %}

<body>
{% block sidebar %}
<div id="navbar-wrapper" class="col col-md-12">
    <div id="wrapper">
        <div id="sidebar-wrapper">
            <aside id="sidebar">
                <ul id="sidemenu" class="sidebar-nav">
                    <li>
                        <a href="{% url 'land:index' %}">
                            <span class="sidebar-icon"><i class="fa fa-dashboard"></i></span>
                            <span class="sidebar-title">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse" href="#submenu-2">
                            <span class="sidebar-icon"><i class="fa fa-users"></i></span>
                            <span class="sidebar-title">Management</span>
                            <b class="caret"></b>
                        </a>
                        <ul id="submenu-2" class="panel-collapse collapse panel-switch" role="menu">
                            <li><a href="{% url 'land:register_land' %}"><i class="fa fa-plus-circle"></i>Register New Land</a></li>
                            <li><a href="{% url 'land:mylands' %}"><i class="fa fa-exchange"></i>Transfer Land</a></li>
                            <li><a href="{% url 'land:mylands' %}"><i class="fa fa-eye"></i>View My Lands</a></li>
                            <li><a href="{% url 'land:profile' %}"><i class="fa fa-user-circle"></i>My Account</a></li>
                        </ul>
                    </li>
                    <li>
                        <a class="accordion-toggle collapsed toggle-switch" data-toggle="collapse" href="#submenu-3">
                            <span class="sidebar-icon"><i class="fa fa-newspaper-o"></i></span>
                            <span class="sidebar-title">Payments</span>
                            <b class="caret"></b>
                        </a>
                        <ul id="submenu-3" class="panel-collapse collapse panel-switch" role="menu">
                            <li><a href="{% url 'land:mylands' %}"><i class="fa fa-caret-right"></i>Pay Land Transfers Fee</a></li>
                            <li><a href="{% url 'payments:history' %}"><i class="fa fa-caret-right"></i>View Payment History</a></li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'land:notification' user=request.user %}">
                            <span class="sidebar-icon"><i class="fa fa-bell-o"></i></span>
                            <span class="sidebar-title">Notifications</span>
                        </a>
                    </li>

                </ul>
            </aside>
        </div>
        <main id="page-content-wrapper" role="main">
        </main>
    </div>
</div>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %} "></script>
<!--material js-->
<script src="{% static 'material/js/material.min.js' %}"></script>
<script src="{% static 'material/js/ripples.min.js' %}"></script>
<script>
    $(function () {
        $.material.init();
    });
</script>

</body>
{% endblock %}

smartland/templates/signup_custom_css.html
<style type="text/css">
.form-signin
{
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
.form-signin .form-signin-heading, .form-signin .checkbox
{
    margin-bottom: 10px;
}
.form-signin .checkbox
{
    font-weight: normal;
}
.form-signin .form-control
{
    position: relative;
    font-size: 16px;
    height: auto;
    padding: 10px;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.form-signin .form-control:focus
{
    z-index: 2;
}
.form-signin input[type="text"]
{
    margin-bottom: -1px;
    border-bottom-left-radius: 0;
    border-bottom-right-radius: 0;
}
.form-signin input[type="password"]
{
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.account-wall
{
    margin-top: 20px;
    padding: 40px 0px 20px 0px;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
}
.login-title
{
    color: #555;
    font-size: 18px;
    font-weight: 400;
    display: block;
}
.profile-img
{
    width: 96px;
    height: 96px;
    margin: 0 auto 10px;
    display: block;
    -moz-border-radius: 50%;
    -webkit-border-radius: 50%;
    border-radius: 50%;
}
.need-help
{
    margin-top: 10px;
}
.new-account
{
    display: block;
    margin-top: 10px;
}

</style>